---
blank_issues_enabled: false
contact_links:
  - name: Network Stack Community Support
    url: https://github.com/developer-academy-unina/network-stack/discussions
    about: Please ask and answer questions here.
